#!/usr/bin/env bash
# Bash script that transfers a file from client to a server using scp

# Check if less than 4 parameters are passed
if [ $# -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables
PATH_TO_FILE="./hello_world.html"
IP="18.204.199.208"
USERNAME="ubuntu"
PATH_TO_SSH_KEY="~/.ssh/school"

# Transfer file using scp with strict host key checking disabled
scp -o StrictHostKeyChecking=no -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME@$IP:~/"