#!/usr/bin/env bash
# Bash script that transfers a file from client to a server using scp

# Check if less than 4 parameters are passed
if [ $# -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables
PATH_TO_FILE="$1"    # Gets the first argument you provide
IP="$2"              # Gets the second argument you provide
USERNAME="$3"        # Gets the third argument you provide
PATH_TO_SSH_KEY="$4" # Gets the fourth argument you provide

# Transfer file using scp with strict host key checking disabled
scp -o StrictHostKeyChecking=no -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME@$IP:~/"